sqa_criteria:
  qc_style:
    repos:
      deepaas:
        container: DEEPaaS-testing
        tox:
          testenv: []
  qc_security:
    repos:
      deepaas:
        container: DEEPaaS-testing
        tox:
          testenv:
            - bandit
